In [1]:
import numpy as np


In [2]:
 # 1)Create a NumPy array containing integers from 0 to 9
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# 2) Create a NumPy array from Python list
lst = [10, 20, 30, 40, 50]
arr2 = np.array(lst)
print(arr2)

[10 20 30 40 50]


In [9]:
# Create a 2D array (3×3) with values from 0 to 8
arr3 = np.arange(9).reshape(3, 3)
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#⃣ Find shape and size of a 5×4 random array
arr4 = np.random.randint(1, 101, (5, 4))
print(arr4)

print("Shape:", arr4.shape)
print("Size:", arr4.size)

[[42 13 80 98]
 [46 54 76 20]
 [30 25 96 23]
 [76 41 86 12]
 [80 40 36 88]]
Shape: (5, 4)
Size: 20


In [11]:
# Access elements from a 3×3 array
arr5 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# a) Second element of first row
print(arr5[0,1])

# b) Third column of second row
print(arr5[1,2])

# c) First two rows & last two columns
print(arr5[:2, 1:])

2
6
[[2 3]
 [5 6]]


In [12]:
# Reshape 1D array of 12 elements into 3×4
arr6 = np.arange(12)
arr6_reshaped = arr6.reshape(3, 4)
print(arr6_reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
# Reshape a 3×3 matrix into 1D
arr7 = np.arange(9).reshape(3,3)
arr7_1d = arr7.reshape(-1)
print(arr7_1d)

[0 1 2 3 4 5 6 7 8]


In [15]:
# Element-wise operations on two (2×3) arrays
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[10,20,30],
                 [40,50,60]])

print("Addition:\n", arr1 + arr2)
print("Subtraction:\n", arr1 - arr2)
print("Multiplication:\n", arr1 * arr2)
print("Division:\n", arr1 / arr2)

Addition:
 [[11 22 33]
 [44 55 66]]
Subtraction:
 [[ -9 -18 -27]
 [-36 -45 -54]]
Multiplication:
 [[ 10  40  90]
 [160 250 360]]
Division:
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [16]:
# Sum, Mean, Standard Deviation
arr9 = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr9))
print("Mean:", np.mean(arr9))
print("Std Dev:", np.std(arr9))

Sum: 150
Mean: 30.0
Std Dev: 14.142135623730951


In [17]:
# Matrix multiplication (2×2)
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

result = np.dot(A, B)
# OR result = A @ B
print(result)

[[19 22]
 [43 50]]


In [18]:
# Transpose of matrix A and B
print("Transpose of A:\n", A.T)
print("Transpose of B:\n", B.T)

Transpose of A:
 [[1 3]
 [2 4]]
Transpose of B:
 [[5 7]
 [6 8]]


In [19]:
# Broadcasting example
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

arr1d = np.array([10, 20, 30])

result = arr2d + arr1d
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [20]:
# Max, Min, Mean of a 4×4 random array
arr13 = np.random.randint(1, 100, (4,4))
print(arr13)

print("Max:", np.max(arr13))
print("Min:", np.min(arr13))
print("Mean:", np.mean(arr13))

[[21 54 16 36]
 [81 68 11 68]
 [59 86 77 94]
 [29 51 50 88]]
Max: 94
Min: 11
Mean: 55.5625


In [21]:
# Row-wise & Column-wise sums
print("Row-wise sum:", np.sum(arr13, axis=1))
print("Column-wise sum:", np.sum(arr13, axis=0))

Row-wise sum: [127 228 316 218]
Column-wise sum: [190 259 154 286]


In [22]:
# Generate 10 random integers between 1 and 50
arr15 = np.random.randint(1, 51, 10)
print(arr15)

[41 28 48 24 26 49 16 13 27  1]


In [23]:
# Generate a 5×5 matrix of random floats (0–1)
arr16 = np.random.rand(5,5)
print(arr16)

[[0.79323369 0.05459212 0.84769108 0.18595079 0.00640347]
 [0.3569156  0.42308661 0.66244721 0.65088673 0.60621205]
 [0.50833073 0.61203974 0.55209989 0.38293714 0.66653394]
 [0.0200687  0.3489685  0.17642056 0.36457113 0.75152134]
 [0.63772107 0.57637395 0.80470245 0.81511615 0.68115269]]
