### 1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [2]:
import numpy as np

arr1 = np.arange(2, 14).reshape(4, 3)
print(arr1)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


### 2. Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [3]:
arr2 = np.random.randint(1, 50, 20)
print("Original Array:", arr2)

arr2[arr2 % 2 != 0] = -1
print("After replacing odd numbers:", arr2)


Original Array: [15  9  6 33 46 15 13 32 40 14 19  2 13 49 41 23  1 34  7 38]
After replacing odd numbers: [-1 -1  6 -1 46 -1 -1 32 40 14 -1  2 -1 -1 -1 -1 -1 34 -1 38]


### 3. Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999

In [4]:
# a. Create a 1d-array of mobile phones prices
prices = np.array([6999, 7500, 11999, 27899, 14999, 9999])
print(prices)


[ 6999  7500 11999 27899 14999  9999]


In [5]:
# b) Convert to float
prices = prices.astype(float)
print(prices)

[ 6999.  7500. 11999. 27899. 14999.  9999.]


In [6]:
# c) Append new mobile price (13999)
prices = np.append(prices, 13999)
print(prices)

[ 6999.  7500. 11999. 27899. 14999.  9999. 13999.]


In [7]:
# d) Reverse the array
prices = prices[::-1]
print(prices)

[13999.  9999. 14999. 27899. 11999.  7500.  6999.]


In [8]:
# e) Apply 18% GST
prices = prices * 1.18
print(prices)

[16518.82 11798.82 17698.82 32920.82 14158.82  8850.    8258.82]


In [9]:
# f) Sort prices in descending order
prices = np.sort(prices)[::-1]
print(prices)

[32920.82 17698.82 16518.82 14158.82 11798.82  8850.    8258.82]


In [10]:
# g) Average mobile phone price
avg_price = np.mean(prices)
print("Average Price:", avg_price)


Average Price: 15743.560000000001


In [11]:

# h) Difference between maximum & minimum price
price_diff = np.max(prices) - np.min(prices)
print("Difference:", price_diff)

Difference: 24662.0


### 4. Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [13]:
arr4 = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr4)
print(indices)

(array([0, 1, 4], dtype=int64),)
